### ISSUE TITLE
mLab is shutting down its Heroku add-on on November 10, 2020

### ISSUE THREAD

**Issue by MicaelJarniac** [synzen/Discord.RSS-Clone#10]
![mLab is shutting down its Heroku add-on on November 10, 2020. You will lose access to your data unless you detach from Heroku or migrate to MongoDB Atlas before then.](https://i.imgur.com/mXe6KUx.png)

> mLab is shutting down its Heroku add-on on November 10, 2020. You will lose access to your data unless you detach from Heroku or migrate to MongoDB Atlas before then.

https://docs.mlab.com/shutdown-of-heroku-add-on/

**Comment by synzen** [comment]
Yes, I've been made aware of this but have yet to make changes to the `README` - thanks for the reminder. Once the changes have been made, I'll close this issue.

**Comment by MicaelJarniac** [comment]
The `app.json` Heroku config thingy for the quick deploy option also uses mLab I believe, so I think that'll also break.

**Comment by Argzero** [comment]
@synzen - Any luck with fixing this? Any projected possible ETA?

**Comment by synzen** [comment]
> 
> 
> @synzen - Any luck with fixing this? Any projected possible ETA?

It's not something I technically fix - all I can do is remove mlab from the Heroku setup and warn users on the README that it's no longer available. For instructions on how to migrate, please follow the link in the original post, that is: https://docs.mlab.com/shutdown-of-heroku-add-on/

https://github.com/synzen/Discord.RSS-Clone/commit/9d1d7cac7aebb42d3ce9649a6c2a3148646e6f4d now has the README updated, along with the removal of mlab from app.json
