### ISSUE TITLE
{subscribers} instead of {subscriptions} in default message

### ISSUE THREAD

**Issue by MicaelJarniac** [synzen/Discord.RSS-Clone#11]
The default message is:

```markdown
:newspaper:  |  **{title}**

{link}

{subscribers}
```

It has the `{subscribers}` placeholder.

However, the actual placeholder that keeps the roles data is `{subscriptions}`, and it even displays a warning about that.

![Warning](https://i.imgur.com/TRK80jW.png)

On the public bot I haven't had this issue, so I'm guessing it has something to do with this clonable version, thus am posting the issue here instead of there.

**Comment by synzen** [comment]
`{subscribers}` was meant to replace `{subscriptions}`, but `{subscriptions}` still work for backwards compatibility. I had forgotten to update the warning to account for this, thanks for bringing it to my attention. It's been fixed now. For future issues related to the web, please redirect your issues to https://github.com/synzen/Discord.RSS-Web. Thanks.
