### ISSUE TITLE
Unable to startup in Heroku

### ISSUE THREAD

**Issue by EPFLRQN** [synzen/Discord.RSS-Clone#3]
![image](https://user-images.githubusercontent.com/45467260/79098045-b3e4c400-7d93-11ea-8110-b0ab7af847dc.png)

**Comment by synzen** [comment]
Apologies for the late reply, I'll try to get on this as soon as I can

**Comment by synzen** [comment]
I am unable to reproduce this issue with Heroku. If you still have issues, feel free to reply to this again.

**Comment by troyunzio** [comment]
![image](https://user-images.githubusercontent.com/77922881/105635214-ec1f4400-5e87-11eb-8e1e-3ed4cbbc0d3a.png)
getting this! I don't know why .

**Comment by troyunzio** [comment]
![image](https://user-images.githubusercontent.com/77922881/105635343-48826380-5e88-11eb-89ec-a48047ecf011.png)
Getting this ,I don't know what. Nothing found in the logs also, please help.

**Comment by amblerkr** [comment]
It's not working at the moment.
If you press the Heroku button and install it automatically, it won't work.
It doesn't work even if you install it manually.
![image](https://user-images.githubusercontent.com/67187038/154955329-298d378e-4665-4331-89a3-e23f07e45b79.png)
![image](https://user-images.githubusercontent.com/67187038/154955658-eeab4930-e4e9-4c0b-a6fe-b64bc73bfadf.png)
