### ISSUE TITLE
Cloudflare error 1020 (access denied)

### ISSUE THREAD

**Issue by esenjin** [synzen/Discord.RSS-Clone#9]
Hello,
When I want to add the feeds from Ankama's sites (especially those of Dofus), I get the following error:
« _The following feed(s) could not be added: 
https://www.dofus.com/fr/rss/news.xml
Reason: Cloudflare - 1020, Access Denied (Custom Firewall Rules)_ »

Here are the worrying feeds: 
- https://www.dofus.com/fr/rss/news.xml
- https://www.dofus.com/fr/rss/changelog.xml
- https://www.dofus.com/fr/rss/devblog.xml

Is there anything that can be done about it?

**Comment by synzen** [comment]
Hi,

Cloudflare is intentionally blocking you from requesting them, and unless the website owner makes an exception (which would defeat the point of Cloudflare), then unfortunately there's nothing you can do. You may see discussion about the failures between RSS and Cloudflare at https://github.com/nyaadevs/nyaa/issues/69 if you'd like more details.
